### ISSUE TITLE
MLX5 Error CQE  

### ISSUE THREAD

**Issue by SSam009** [Juniper/warp17#81] opened 2018-09-11 17:35 UTC
Environment: 

Red Hat Enterprise Linux Server release 7.5 (Maipo)
dpdk-stable-17.11.3/
warp17-dev-common/

I am not sure it's related to the warp17, getting Following Stack Trace with Mellanox Cards before starting the test:  

start tests port 1
USER1: Test Case 0 started on port 1
Tests started on port 1
start tests port 0
USER1: Test Case 0 started on port 0
USER1: Port 1, Test Case 0 "PASSED"!
Tests started on port 0
show tests ui

warp17> MLX5 Error CQE: at [0x7f6a7d20c000], len=64
00000000: 00 73 65 65 6E 00 00 00 00 00 00 00 00 00 00 00 | .seen...........
00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
00000020: 00 00 00 13 00 00 00 00 00 00 00 00 00 00 00 00 | ................
00000030: 00 00 00 00 9D 00 53 04 0A 00 15 42 00 19 B0 D2 | ......S....B....
MLX5 Error CQE: at [0x7f5b64e01080], len=64
00000000: 00 73 65 65 6E 00 00 00 00 00 00 00 00 00 00 00 | .seen...........
00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
00000020: 00 00 00 0C 00 00 00 00 00 00 00 00 00 00 00 00 | ................
00000030: 00 00 00 00 9D 00 53 04 0A 00 15 34 00 5A 98 D2 | ......S....4.Z..
[root@localhost warp17]# 

**logs from /var/log/messages** 
[   21.365907] mlx5_core 0000:08:00.0 ens1: Link up
[   27.947560] mlx5_core 0000:82:00.0 ens3: Link up
[   34.545575] warning: `lldpd' uses legacy ethtool link settings API, link modes are only partially reported
[  155.858105] Bits 55-60 of /proc/PID/pagemap entries are about to stop being page-shift some time soon. See the linux/Documentation/vm/pagemap.txt for details.
[  302.883300] mlx5_core 0000:82:00.0: mlx5_eq_int:676:(pid 0): CQ error on CQN 0x31, syndrome 0x1
[  302.883317] mlx5_core 0000:08:00.0: mlx5_eq_int:676:(pid 2899): CQ error on CQN 0x38, syndrome 0x1
[  302.902631] mlx5_core 0000:08:00.0: mlx5_tracer_handle_traces:714:(pid 440): FWTracer: Events were lost
[  302.914041] mlx5_core 0000:82:00.0: mlx5_tracer_handle_traces:714:(pid 301): FWTracer: Events were lost
[  663.120315] perf: interrupt took too long (2503 > 2500), lowering kernel.perf_event_max_sample_rate to 79000
[  701.832732] perf: interrupt took too long (3138 > 3128), lowering kernel.perf_event_max_sample_rate to 63000
[  736.781194] mlx5_core 0000:08:00.0: mlx5_eq_int:676:(pid 4132): CQ error on CQN 0x38, syndrome 0x1
[  736.781500] mlx5_core 0000:82:00.0: mlx5_eq_int:676:(pid 0): CQ error on CQN 0x31, syndrome 0x1
[ 1964.486675] perf: interrupt took too long (3925 > 3922), lowering kernel.perf_event_max_sample_rate to 50000

**Comment by davvore33** [comment] 2019-03-07 10:38
Hi @SSam009, I've fixed [lately](https://github.com/Juniper/warp17/commit/bae37edfd1dfd869875ff920813fb4ee871c02e4) a bug related to Mellanox (and non) configuration, can you try to replicate this with the latest `dev/common` branch?

**Comment by janekmi** [comment] 2019-12-18 15:56
@davvore33, can you elaborate a bit what was the nature of this issue? I'm experiencing a similar issue with other software and I would love to know what causes it.

**Comment by davvore33** [comment] 2019-12-19 09:37
Hi @janekmi, we were imposing wrong offloads to the NIC in particular `DEV_RX_OFFLOAD_VLAN_STRIP`, although it's been quite a long time, I'm not sure if it was that the problem, let me know if you'll find anything more about this

**Comment by janekmi** [comment] 2020-02-17 14:51
After proper debug I have found the root cause. It all boils down to CQ overrun. 
Nothing fancy.

**Comment by davvore33** [comment] 2020-02-18 09:02
That's annoying, so if we are good I'd close the issue @janekmi

**Comment by janekmi** [comment] 2020-02-18 15:45
Agreed.

**Closed as completed** 2020-02-19 08:49 UTC
